# Generated by Django 5.2.17 on 2026-09-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=64, verbose_name='nom')),
                ('symbol', models.CharField(blank=True, max_length=8, verbose_name='symbole')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='0 pour GNF / XOF, 2 pour USD / EUR.', verbose_name='décimales')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'devise',
                'verbose_name_plural': 'devises',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24, verbose_name='taux')),
                ('as_of', models.DateField(verbose_name='date du taux')),
                ('source', models.CharField(default='fawazahmed0', max_length=40, verbose_name='source')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='récupéré le')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_base', to='currencies.currency', verbose_name='de')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_quote', to='currencies.currency', verbose_name='vers')),
            ],
            options={
                'verbose_name': 'taux de change',
                'verbose_name_plural': 'taux de change',
                'ordering': ['-as_of'],
                'indexes': [models.Index(fields=['base', 'quote', '-as_of'], name='currencies__base_id_382d7f_idx')],
                'constraints': [models.UniqueConstraint(fields=('base', 'quote', 'as_of'), name='uniq_rate_base_quote_date')],
            },
        ),
    ]
