# Generated by Django 5.2.17 on 2026-09-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('sku', models.CharField(blank=True, max_length=40, verbose_name='référence')),
                ('unit', models.CharField(default='pièce', max_length=20, verbose_name='unité')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="prix d'achat (coût moyen)")),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='prix de vente')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16, verbose_name='quantité en stock')),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, verbose_name="seuil d'alerte")),
                ('category', models.CharField(blank=True, max_length=60, verbose_name='catégorie')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivé')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='activities.activity')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='prix de vente unitaire')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='coût unitaire (figé)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='remise')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_lines', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'ligne de vente',
                'verbose_name_plural': 'lignes de vente',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('type', models.CharField(choices=[('in', 'Entrée (achat)'), ('out', 'Sortie (vente)'), ('adjust', 'Ajustement (perte, casse, inventaire)')], max_length=6, verbose_name='type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='quantité')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='coût unitaire')),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='stock après')),
                ('occurred_on', models.DateField(verbose_name='date')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['activity', 'is_archived'], name='inventory_p_activit_405666_idx'),
        ),
    ]
