# Generated by Django 5.2.17 on 2026-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('in', 'Entrée (achat)'), ('out', 'Sortie (vente)'), ('adjust', 'Ajustement (perte, casse, inventaire)'), ('personal', 'Consommation personnelle')], max_length=8, verbose_name='type'),
        ),
    ]
