# Generated by Django 5.2.17 on 2026-09-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='téléphone')),
                ('kind', models.CharField(choices=[('client', 'Client'), ('supplier', 'Fournisseur'), ('both', 'Client et fournisseur')], default='client', max_length=8, verbose_name='type')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivé')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tiers',
                'verbose_name_plural': 'tiers',
                'ordering': ['name'],
            },
        ),
    ]
