# Generated by Django 5.2.17 on 2026-09-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('contacts', '0001_initial'),
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('direction', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=3, verbose_name='sens')),
                ('is_system', models.BooleanField(default=False, verbose_name='catégorie système')),
                ('activity', models.ForeignKey(blank=True, help_text='Vide = catégorie disponible pour toutes les activités.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='activities.activity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=60, verbose_name='nom')),
                ('is_cash', models.BooleanField(default=False, verbose_name='espèces / liquide')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'moyen de paiement',
                'verbose_name_plural': 'moyens de paiement',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('direction', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=3, verbose_name='sens')),
                ('kind', models.CharField(choices=[('simple', 'Entrée / sortie simple'), ('sale', 'Vente'), ('purchase', 'Achat / réapprovisionnement'), ('settlement', "Règlement d'une dette"), ('adjustment', 'Ajustement')], default='simple', max_length=12, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant saisi')),
                ('amount_activity', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant (devise activité)')),
                ('amount_base', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant (devise principale)')),
                ('fx_rate_to_base', models.DecimalField(decimal_places=12, default=1, max_digits=24, verbose_name='taux vers devise principale')),
                ('fx_date', models.DateField(verbose_name='date du taux')),
                ('occurred_on', models.DateField(verbose_name="date de l'opération")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('is_credit', models.BooleanField(default=False, verbose_name='à crédit')),
                ('is_settled', models.BooleanField(default=False, verbose_name='soldée')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='activities.activity')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='currencies.currency')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='contacts.party')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.paymentmethod')),
                ('settles', models.ForeignKey(blank=True, help_text='Transaction à crédit que ce règlement vient solder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['activity', '-occurred_on'], name='finance_tra_activit_bae42a_idx'), models.Index(fields=['activity', 'direction', 'kind'], name='finance_tra_activit_c294b4_idx')],
            },
        ),
    ]
