# Generated by Django 5.2.17 on 2026-09-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_voided_at_transaction_voided_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('simple', 'Entrée / sortie simple'), ('sale', 'Vente'), ('purchase', 'Achat / réapprovisionnement'), ('settlement', "Règlement d'une dette"), ('adjustment', 'Ajustement'), ('opening_balance', 'Solde initial (report)')], default='simple', max_length=20, verbose_name='type'),
        ),
    ]
