# Generated by Django 5.2.17 on 2026-09-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='montant déjà réglé'),
        ),
    ]
