# Generated by Django 5.2.17 on 2026-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_backfill_settled_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('simple', 'Entrée / sortie simple'), ('sale', 'Vente'), ('purchase', 'Achat / réapprovisionnement'), ('settlement', "Règlement d'une dette"), ('adjustment', 'Ajustement'), ('opening_balance', 'Solde initial (report)'), ('personal_use', 'Consommation personnelle')], default='simple', max_length=20, verbose_name='type'),
        ),
    ]
