# Generated by Django 5.2.17 on 2026-09-07 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code de réinitialisation',
                'verbose_name_plural': 'codes de réinitialisation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'code'], name='accounts_pa_user_id_193f58_idx')],
            },
        ),
    ]
