# Generated by Django 5.2.17 on 2026-09-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('type', models.CharField(choices=[('commerce', 'Commerce'), ('service', 'Service / prestation'), ('salary', 'Salaire / revenu fixe'), ('rental', 'Location'), ('farming', 'Agriculture / élevage'), ('household', 'Ménage / dépenses'), ('other', 'Autre')], default='other', max_length=16, verbose_name='type')),
                ('has_inventory', models.BooleanField(default=False, verbose_name='module inventaire')),
                ('has_debts', models.BooleanField(default=False, verbose_name='module crédits & dettes')),
                ('has_budget', models.BooleanField(default=False, verbose_name='module budget')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='solde de caisse initial')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivée')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='currencies.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activité',
                'verbose_name_plural': 'activités',
                'ordering': ['-created_at'],
            },
        ),
    ]
