# Generated by Django 5.2.17 on 2026-09-07 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('currencies', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('period', models.CharField(choices=[('week', 'Semaine'), ('month', 'Mois'), ('year', 'Année')], default='month', max_length=5, verbose_name='période')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant prévu')),
                ('starts_on', models.DateField(verbose_name='à partir du')),
                ('activity', models.ForeignKey(blank=True, help_text='Vide = budget global (toutes activités).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='activities.activity')),
                ('category', models.ForeignKey(blank=True, help_text="Vide = budget de dépenses global de l'activité.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'ordering': ['-starts_on'],
            },
        ),
    ]
